name: DrMemory & GTest
on:
  push:
    branches-ignore:
      - '**-coverage-report'
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.17.x'
      - name: Set up Curl
        run: |
          sudo apt install curl
      - name: Install DrMemory
        run: |
          curl -OL https://github.com/DynamoRIO/drmemory/releases/download/release_2.4.0/DrMemory-Linux-2.4.0-2.tar.gz
          tar -xvzf DrMemory-Linux-2.4.0-2.tar.gz
      - name: Build Tests
        run: |
          cd ./modules
          cmake .
          cmake --build . --target runParacModulesTests -- -j 9
      - name: Run Tests
        run: |
          ./modules/tests/tests/runParacModulesTests
      - name: Run DrMemory for Tests
        run: |
          ./DrMemory-Linux-2.4.0-2/bin/drmemory -- ./modules/parac-modules-tests/tests/runParacModulesTests
